<?php
/**
 * The template for displaying the footer on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/footer.scss.
 * The "Footer Columns" generated by PHP can be configured in functions.php.
 *
 * Contains the footer of the site as well as WP's required code and the closing body and HTML tags.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage fc_live
 * @since 1.0.0
 */
?>

<!--Start Footer-->
<footer class="footer">
    <div class="text-center mx-auto text-white">
        <div class="w-24 md:w-32 lg:w-72 text-center mx-auto">
        <img class = "mx-auto text-center" src="<?php the_field('foothills_logo', 'options'); ?>"
                 alt="Company Logo">
    </div>
        <div>&copy; <?php echo date("Y");?> Foothills Church</div>
        <a class = "inline" href="https://foothillschurch.com/">Back to Foothills Church</a> | <div class="footer-inline"> <?php wp_nav_menu( array( 'theme_location' => 'footer-column-1' ) ); ?></div>
    </div>
</footer>
<!--End Footer-->


<!--Wordpress Requires This-->
<?php wp_footer(); ?>

</body>
</html>